### ISSUE TITLE
AttributeError: module 'icecube.phys_services' has no attribute 'I3SPRNGRandomService'

### ISSUE THREAD

**Issue by fiedl** [fiedl/hole-ice-scripts#10]
When running the propagation script in zeuthen (#9), the random-number generator is not found.

```
[2022-09-09 17:24:37] fiedl@kepler00 ~/icecube/hole-ice-scripts
▶ ~/icecube/icetray-build/env-shell.sh
▶ scripts/generate_photons.py
Traceback (most recent call last):
  File "scripts/generate_photons.py", line 63, in <module>
    main()
  File "scripts/generate_photons.py", line 16, in main
    random_number_generator = phys_services.I3SPRNGRandomService(
AttributeError: module 'icecube.phys_services' has no attribute 'I3SPRNGRandomService'
```

_Originally posted by @fiedl in https://github.com/fiedl/hole-ice-scripts/issues/9#issuecomment-1242122032_

**Comment by fiedl** [comment]
Checking `cmake`:

```
[2022-09-09 16:39:46] fiedl@kepler00 ~/icecube/icetray-build
▶ /cvmfs/icecube.opensciencegrid.org/py3-v4.2.1/setup.sh
▶ module load cuda/11.6
▶ export OPENCL_VENDOR_PATH=/cvmfs/icecube.opensciencegrid.org/distrib/OpenCL_RHEL_7_x86_64/etc/OpenCL/vendors
▶ cmake -D CMAKE_BUILD_TYPE=Debug -D SYSTEM_PACKAGES=true ../icetray
-- gsl
-- + gsl/gsl_rng.h found at /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/include
-- + /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/libgsl.so
--
-- sprng
-- - sprng/sprng.h not found in include/sprng-2.0a
-- + /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/libsprng.a
--
-- sprng
-- - sprng/sprng.h not found in include
-- + /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/libsprng.a
--
-- + phys-services
-- +-- sprng *not* found, omitting optional SPRNGRandomService
```

The random generator is not found 👎

**Comment by fiedl** [comment]
This has been discussed in https://icecube-spno.slack.com/archives/C02KQL9KN/p1587571467205400:

> sprng is not present in the py3-series toolsets, and so can’t be found. many existing scripts assume it is there and so attempt to use it at runtime, and fail because it’s not there. some, like the simprod clsim wrapper linked above, have a command line switch to control which RNG is used. some don’t.
>
> It’s falling back to `I3GSLRandomService`.

So, let's try to use `I3GSLRandomService` in this script.

**Comment by fiedl** [comment]
workaround: https://github.com/fiedl/hole-ice-scripts/commit/de2bdd398d0c9af8ff213833d2b9ed85a438f360
