### ISSUE TITLE
ImportError: cannot import name 'I3CLSimOpenCLDevice' from 'icecube.clsim'

### ISSUE THREAD

**Issue by fiedl** [fiedl/hole-ice-scripts#8]
How to reproduce:

1. Clone this repository
2. Build icetray locally (#1)
3. Start icetray env shell
4. Run script `scripts/propagate_photons.py` locally:

```
[2022-09-08 00:12:29] fiedl@fiedl-mbp ~/icecube/hole-ice-scripts master ⚡ f823690
▶ source ~/py3/bin/activate && ~/icecube/icetray-build/env-shell.sh
▶ scripts/generate_photons.py
▶ scripts/propagate_photons.py
Traceback (most recent call last):
  File "/Users/fiedl/icecube/hole-ice-scripts/scripts/propagate_photons.py", line 92, in <module>
    main()
  File "/Users/fiedl/icecube/hole-ice-scripts/scripts/propagate_photons.py", line 28, in main
    tray.Add(
  File "/Users/fiedl/icecube/icetray-build/lib/I3Tray.py", line 107, in Add
    return method(_type, _name, **kwargs)
  File "/Users/fiedl/icecube/icetray-build/lib/I3Tray.py", line 224, in AddSegment
    return _segment(self, _name, **kwargs)
  File "/Users/fiedl/icecube/icetray-build/lib/icecube/clsim/traysegments/I3CLSimMakePhotons.py", line 302, in I3CLSimMakePhotons
    converters = setupPropagators(RandomService, clsimParams,
  File "/Users/fiedl/icecube/icetray-build/lib/icecube/clsim/traysegments/common.py", line 430, in setupPropagators
    openCLDevices = configureOpenCLDevices(
  File "/Users/fiedl/icecube/icetray-build/lib/icecube/clsim/traysegments/common.py", line 13, in configureOpenCLDevices
    from icecube.clsim import I3CLSimOpenCLDevice
ImportError: cannot import name 'I3CLSimOpenCLDevice' from 'icecube.clsim' (/Users/fiedl/icecube/icetray-build/lib/icecube/clsim/__init__.py)
```

This script does work when running in docker (#2), but fails when running locally (#1).

**Comment by fiedl** [comment]
The python bindings do exist:
https://github.com/icecube/icetray/blob/15a14410d8d57cfcb52822545a4ccc5e4920a44a/clsim/private/pybindings/I3CLSimOpenCLDevice.cxx

Why can't the `I3CLSimOpenCLDevice` be imported?

**Comment by fiedl** [comment]
https://icecube-spno.slack.com/archives/C02KQL9KN/p1606666919276900 suggests

> You appear to have made your … build in a such a way that OpenCL was not found.

**Comment by fiedl** [comment]
Not my choice, however:

```
[2022-09-08 00:37:04] fiedl@fiedl-mbp ~/icecube/icetray-build
▶ cmake -D CMAKE_BUILD_TYPE=Debug -D SYSTEM_PACKAGES=true ~/icecube/icetray
-- OpenCL
-- + Disabling OpenCL on Apple Silicon. Support is forthcoming.
```

See also: https://github.com/icecube/icetray/blob/main/cmake/tools/opencl.cmake

**Comment by fiedl** [comment]
But why is it disabled?

https://developer.apple.com/forums/thread/694866

> OpenGL and OpenCL still run on Apple Silicon for now
>
> OpenGL and OpenCL were deprecated in macOS 10.14 and may be removed in the future, please use Metal
